--PL9 EX1
SELECT NVL(LOCALCOMPRA, 'Desconhecido') AS "LOCAL_COMPRA", COUNT(titulo) AS "QUANTIDADE_CD"
FROM CD
GROUP BY LOCALCOMPRA;

--PL9 EX2
SELECT NVL(LOCALCOMPRA, 'Desconhecido') AS "LOCAL_COMPRA", COUNT(titulo) AS "QUANTIDADE_CD"
FROM CD
GROUP BY LOCALCOMPRA
ORDER BY QUANTIDADE_CD DESC;

--PL9 EX3
SELECT NVL(LOCALCOMPRA, 'Desconhecido') AS "LOCAL_COMPRA", COUNT(DISTINCT IDEDITORA) AS "QUANTIDADE_EDITORAS"
FROM CD
GROUP BY LOCALCOMPRA
ORDER BY QUANTIDADE_EDITORAS;

--PL9 EX4
SELECT LOCALCOMPRA        AS "LOCAL_COMPRA",
       COUNT(LOCALCOMPRA) AS "QUANTIDADE_CD",
       SUM(VALORPAGO)     AS "TOTAL",
       MAX(VALORPAGO)     AS "MAIOR"
FROM CD
WHERE LOCALCOMPRA IS NOT NULL
GROUP BY LOCALCOMPRA
ORDER BY QUANTIDADE_CD DESC;

--PL9 EX5
SELECT CD.CODCD, INTERPRETE, Count(NRMUSICA) as QUANTIDADE_MUSICAS
FROM CD
         INNER JOIN MUSICA ON CD.CODCD = MUSICA.CODCD
GROUP BY CD.CODCD, MUSICA.INTERPRETE
ORDER BY CD.CODCD;

--PL9 EX6
SELECT NVL(LOCALCOMPRA, 'Desconhecido') AS "LOCAL_COMPRA", COUNT(titulo) AS "QUANTIDADE_CD"
FROM CD
GROUP BY LOCALCOMPRA
HAVING COUNT(titulo) > 2;

--PL9 EX7
SELECT NVL(LOCALCOMPRA, 'Desconhecido'), SUM(VALORPAGO) AS "TOTAL"
FROM CD
GROUP BY LOCALCOMPRA
HAVING AVG(VALORPAGO) < 10;

--PL9 EX8
SELECT NVL(LOCALCOMPRA, 'Desconhecido'), SUM(VALORPAGO) AS "TOTAL"
FROM CD
GROUP BY LOCALCOMPRA
HAVING COUNT(TITULO) > 2;

--PL9 EX9
SELECT CD.CODCD, INTERPRETE
FROM CD
         INNER JOIN MUSICA ON CD.CODCD = MUSICA.CODCD
GROUP BY CD.CODCD, MUSICA.INTERPRETE
HAVING Count(NRMUSICA) = 1
ORDER BY CD.CODCD;

--PL9 EX10
SELECT DISTINCT INTERPRETE
FROM CD
         INNER JOIN MUSICA ON CD.CODCD = MUSICA.CODCD
GROUP BY CD.CODCD, MUSICA.INTERPRETE
HAVING Count(NRMUSICA) = 1
   AND REGEXP_LIKE(INTERPRETE, '^[eElL]')
ORDER BY INTERPRETE;

--PL9 EX11
SELECT TO_CHAR(DATACOMPRA, 'DAY') AS "DIA_SEMANA", COUNT(TITULO) AS "QTD_CD_COMPRADOS"
FROM CD
WHERE LOCALCOMPRA IS NOT NULL
GROUP BY TO_CHAR(DATACOMPRA, 'DAY')
HAVING COUNT(TITULO) >= 2

--PL9 EX12

