--A
SELECT c.NOME, c.CONCELHO, c.LOCALIDADE
FROM CLIENTE c
         INNER JOIN RESERVA r1 on c.NIF = r1.CLIENTENIF
WHERE r1.QUARTOID IN (SELECT r2.QUARTOID FROM RESERVA r2 WHERE r2.CLIENTENIF = 296837970)
  AND r1.ESTADO = 'Finalizada'
  AND r1.CLIENTENIF <> 296837970;

--B
WITH CAMAREIRA_RESERVAID AS (SELECT r.ID, il.CAMAREIRANIF, EXTRACT(MONTH FROM r.DATAINICIO) AS MES, q.TIPOQUARTOID
                             FROM INTERVENCAOLIMPEZA il
                                      INNER JOIN PEDIDOINTERVENCAO pi on pi.FUNCIONARIONIF = il.CAMAREIRANIF
                                      INNER JOIN RESERVA r on r.ID = pi.RESERVAID
                                      INNER JOIN QUARTO q on q.ID = r.QUARTOID
                             WHERE (r.DATAFIM - r.DATAINICIO) >
                                   (SELECT AVG(r2.DATAFIM - r2.DATAINICIO) FROM RESERVA r2)),
     CAMAREIRA_COUNTINTERVENCOES_PORMES AS (SELECT COUNT(t.ID) AS cont, t.CAMAREIRANIF, t.MES, t.TIPOQUARTOID
                                            FROM CAMAREIRA_RESERVAID t
                                            WHERE MES BETWEEN EXTRACT(MONTH FROM (ADD_MONTHS(SYSDATE, -6))) AND EXTRACT(MONTH FROM SYSDATE)
                                            GROUP BY t.CAMAREIRANIF, t.MES, t.TIPOQUARTOID)
SELECT t2.MES, f.NOME, t2.cont AS "CONTAGEM", t2.TIPOQUARTOID AS "TIPO DE QUARTO"
FROM CAMAREIRA_COUNTINTERVENCOES_PORMES t2
         INNER JOIN FUNCIONARIO f ON t2.CAMAREIRANIF = f.NIF
         INNER JOIN (SELECT t3.MES, MAX(t3.cont) AS CONT2, t3.TIPOQUARTOID
                     FROM CAMAREIRA_COUNTINTERVENCOES_PORMES t3
                              INNER JOIN FUNCIONARIO f2 ON t3.CAMAREIRANIF = f2.NIF
                     GROUP BY t3.MES, t3.TIPOQUARTOID) ccp ON ccp.MES = t2.MES AND t2.cont = ccp.CONT2 AND t2.TIPOQUARTOID = ccp.TIPOQUARTOID
ORDER BY t2.MES DESC;