--A
SELECT *
FROM PEDIDOINTERVENCAO pi
WHERE pi.FUNCIONARIONIF IN (SELECT FUNCIONARIOMANUTENCAONIF
                            FROM INTERVENCAOMANUTENCAO im
                            WHERE pi.FUNCIONARIONIF = im.FUNCIONARIOMANUTENCAONIF
                              AND im.DATA > SYSDATE - 2)
  AND pi.ESTADO = 'em aberto'
ORDER BY pi.ID;

--B
SELECT c.NOME       AS "NOME DO CLIENTE",
       r.DATAINICIO AS "DATA DE RESERVA",
       CASE
           WHEN (SELECT TIPOQUARTOID FROM QUARTO q WHERE q.ID = r.QUARTOID) = 2 THEN c.LOCALIDADE
           END      AS "ZONA DO PAÍS"
FROM CLIENTE c
         INNER JOIN RESERVA r on c.NIF = r.CLIENTENIF
WHERE (EXTRACT(MONTH FROM r.DATAINICIO) = 4)
   OR (EXTRACT(MONTH FROM r.DATAINICIO) = 6)
ORDER BY c.NOME ASC, r.DATAINICIO DESC;