CREATE OR REPLACE TRIGGER TRGEPOCASNAOSOBREPOSTAS
    AFTER INSERT OR UPDATE
    ON EPOCA
DECLARE
    C NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO C
    FROM EPOCA E
    WHERE EXISTS(SELECT 1
                 FROM EPOCA E2
                 WHERE (E.DATA_INI BETWEEN E2.DATA_INI AND E2.DATA_FIM OR E.DATA_FIM
                     BETWEEN E2.DATA_INI AND E2.DATA_FIM)
                   AND E2.ROWID <> E.ROWID);
    IF C > 0 THEN RAISE_APPLICATION_ERROR(-20021, 'INSERT FAILED BECAUSE SELECTED DATES OVERLAP EXISTENT ONES'); END IF;
END;

-- TESTS
-- ALL OF THESE SHOULD FAIL

INSERT INTO EPOCA
VALUES (11, ' EPOCA 5 ', TO_DATE('2020-09-02', 'yyyy-mm-dd'), TO_DATE('2020-12-27', 'yyyy-mm-dd'));

UPDATE EPOCA
SET DATA_INI=TO_DATE('2020-09-05', 'yyyy-mm-dd'),
    DATA_FIM= TO_DATE('2020-12-10', 'yyyy-mm-dd')
WHERE ID = 3;