-- ASSUME QUE AS LINHAS DE FATURA E DE CONSUMO SEJAM PREVIAMENTE INTRODUZIDAS EM SISTEMA, VISTO QUE SEMPRE QUE É
-- EFETUADO UM CONSUMO É GERADA UMA LINHA DE CONSUMO E ESSA CONTA CONSUMO VAI CONSTAR NAS LINHAS DE CADA FATURA DE
-- CADA CLIENTE. PARA QUE ESTE PROCEDURE FUNCIONE E CONTE COM AS CONDIÇÕES MENCIONADAS TIVEMOS DE ADICIONAR INSERTS
-- PARA AS TABELAS LINHA_FATURA E LINHA_CONSUMO
CREATE OR REPLACE PROCEDURE PRCCHECKOUT(LINHA_RESERVA IN RESERVA%ROWTYPE)
AS
    LINHA_INVALIDA EXCEPTION;
    CONSUMO_TOTAL NUMBER;
    VALOR_ESTADIA NUMBER;
BEGIN
    -- COLOCA EM CONSUMO_TOTAL O VALOR TOTAL DE TODOS OS CONSUMOS EFETUADOS
    SELECT COUNT(LCC.QUANTIDADE * LCC.PRECO_UNITARIO)
    INTO CONSUMO_TOTAL
    FROM LINHA_CONTA_CONSUMO LCC
             JOIN CONTA_CONSUMO CC ON CC.ID = LCC.ID_CONTA_CONSUMO
    WHERE CC.ID_RESERVA = LINHA_RESERVA.ID;

    -- CALCULA O VALOR TOTAL A PAGAR PELA ESTADIA TENDO EM CONTA A ÉPOCA DO ANO EM QUE A RESERVA FOI FEITA, USANDO
    -- UMA INNER QUERY (SELECT DENTRO DE SELECT)
    SELECT PCTQ.PRECO * (TRUNC(LINHA_RESERVA.DATA_SAIDA) - TRUNC(LINHA_RESERVA.DATA_SAIDA))
    INTO VALOR_ESTADIA
    FROM PRECO_EPOCA_TIPO_QUARTO PCTQ
    WHERE PCTQ.ID_TIPO_QUARTO = LINHA_RESERVA.ID_TIPO_QUARTO
      AND PCTQ.ID_EPOCA = (SELECT E.ID
                           FROM EPOCA E
                           WHERE (LINHA_RESERVA.DATA_ENTRADA) BETWEEN E.DATA_INI AND E.DATA_FIM
    );

    -- CRIA O CHECKOUT DO QUARTO/RESERVA
    INSERT INTO CHECKOUT VALUES (LINHA_RESERVA.ID, LINHA_RESERVA.DATA_SAIDA, '', 0);

    -- CRIA A FATURA ASSOCIADO À RESERVA
    INSERT INTO FATURA VALUES (1, 1, SYSDATE, LINHA_RESERVA.ID_CLIENTE, LINHA_RESERVA.ID, VALOR_ESTADIA, CONSUMO_TOTAL);

END;

COMMIT;