CREATE OR REPLACE FUNCTION FNCOBTERREGISTOMENSALCAMAREIRA(MES_PARAM INT, ANO_PARAM INT) RETURN SYS_REFCURSOR
    IS
    CURSOR_CAMAREIRA SYS_REFCURSOR;
BEGIN

    -- COLOCA NO CURSOS CAMAREIRA O ID, O NOME, O SOMATORIO DE TODOS OS REGISTOS EFETUADOS, A DATA DO PRIMEIRO
    -- REGISTO E A DATA DO ULTIMO REGISTO. EFETUA UM JOIN NAS TABELAS FUNCIONARIO PARA IR BUSCAR NOME E
    -- LINHA_CONTA_CONSUMO PARA IR BUSCAR A RESTANTE INFORMACAO. OS DADOS ESTAO AGRUPADOS PELO NOME/ID DA CAMAREIRA
    OPEN CURSOR_CAMAREIRA FOR
        SELECT C.ID,
               F.NOME,
               SUM(LCC.QUANTIDADE * LCC.PRECO_UNITARIO) AS CONSUMO_TOTAL,
               MIN(LCC.DATA_REGISTO)                    AS
                                                           PRIMEIRO_REGISTO,
               MAX(LCC.DATA_REGISTO)                    AS ULTIMO_REGISTO
        FROM CAMAREIRA C
                 JOIN FUNCIONARIO F ON F.ID = C.ID
                 JOIN LINHA_CONTA_CONSUMO LCC ON LCC.ID_CAMAREIRA = C.ID
        WHERE (ANO_PARAM IS NULL AND EXTRACT(MONTH FROM LCC.DATA_REGISTO) = MES_PARAM AND EXTRACT(YEAR FROM LCC
            .DATA_REGISTO) = EXTRACT
                                 (YEAR FROM
                                  SYSDATE) -
                             1)
           OR (ANO_PARAM IS NOT NULL AND EXTRACT(MONTH FROM LCC.DATA_REGISTO) = MES_PARAM AND EXTRACT(YEAR FROM LCC
            .DATA_REGISTO) =
                                                                                              ANO_PARAM)
        GROUP BY C.ID, F.NOME;
    RETURN CURSOR_CAMAREIRA;
END;

-- TEST
DECLARE
    CAMAREIRA_INFO SYS_REFCURSOR;
    CAMAREIRA_ID   CAMAREIRA.ID%TYPE;
    CAMAREIRA_NOME FUNCIONARIO.NOME%TYPE;
    CONTAGEM_EUR   NUMBER;
    DATA_PRIMEIRO  DATE;
    DATA_ULTIMO    DATE;
BEGIN
    CAMAREIRA_INFO := FNCOBTERREGISTOMENSALCAMAREIRA(12, 2020);
    FETCH CAMAREIRA_INFO INTO
        CAMAREIRA_ID,CAMAREIRA_NOME,CONTAGEM_EUR,DATA_PRIMEIRO,DATA_ULTIMO;
    IF NOT CAMAREIRA_INFO%NOTFOUND THEN
        DBMS_OUTPUT.PUT_LINE(
                    CAMAREIRA_ID || ' - ' || CAMAREIRA_NOME || ' - ' || CONTAGEM_EUR || ' - ' || DATA_PRIMEIRO || '-' ||
                    ' ' || DATA_ULTIMO);
    ELSE
        RAISE NO_DATA_FOUND;
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NAO ENCONTRADO');
END;