-- ASSUME QUE AS LINHAS DE FATURA E DE CONSUMO SEJAM PREVIAMENTE INTRODUZIDAS EM SISTEMA, VISTO QUE SEMPRE QUE É
-- EFETUADO UM CONSUMO É GERADA UMA LINHA DE CONSUMO E ESSA CONTA CONSUMO VAI CONSTAR NAS LINHAS DE CADA FATURA DE
-- CADA CLIENTE. PARA QUE ESTE PROCEDURE FUNCIONE E CONTE COM AS CONDIÇÕES MENCIONADAS TIVEMOS DE ADICIONAR INSERTS
-- PARA A TABELA LINHA_CONSUMO
CREATE OR REPLACE PROCEDURE PRCCHECKOUT(LINHA_RESERVA IN RESERVA%ROWTYPE)
AS
    LINHA_INVALIDA EXCEPTION;
    C_DADOSFATURAR        SYS_REFCURSOR;
    CONSUMO_TOTAL         NUMBER;
    VALOR_ESTADIA         NUMBER;
    AUX_NUMFATURA         NUMBER;
    AUX_IDFATURA          NUMBER;
    AUX_CONTADOR_LINHAFAT NUMBER;
    AUX_IDCC              NUMBER;
    AUX_VALORCONSUMO      NUMBER;
    AUX_LCC               NUMBER;
BEGIN

    -- VAMOS OBTER E CALCULAR O ID E NUM DA FATURA A GERAR
    SELECT MAX(F.ID), MAX(F.NUMERO) INTO AUX_IDFATURA, AUX_IDFATURA FROM FATURA F;
    IF AUX_IDFATURA IS NULL AND AUX_NUMFATURA IS NULL THEN AUX_IDFATURA := 0; AUX_NUMFATURA := 0; END IF;
    AUX_IDFATURA := AUX_IDFATURA + 1;
    AUX_NUMFATURA := AUX_NUMFATURA + 1;

    -- VAMOS OBTER O ID DA CONTA CONSUMO ASSOCIADO A ESTA RESERVA
    SELECT CC.ID INTO AUX_IDCC FROM CONTA_CONSUMO CC WHERE CC.ID_RESERVA = LINHA_RESERVA.ID;

    -- COLOCA EM CONSUMO_TOTAL O VALOR TOTAL DE TODOS OS CONSUMOS EFETUADOS
    SELECT COUNT(LCC.QUANTIDADE * LCC.PRECO_UNITARIO)
    INTO CONSUMO_TOTAL
    FROM LINHA_CONTA_CONSUMO LCC
             JOIN CONTA_CONSUMO CC ON CC.ID = LCC.ID_CONTA_CONSUMO
    WHERE CC.ID_RESERVA = LINHA_RESERVA.ID;

    -- VAMOS COLOCAR NO CURSOS C_DADOSFATURAR A LINHA DA CONTA CONSUMO E O VALOR ASSOCIADO A ESSA LINHA PARA COLOCAR
    -- NA FATURA
    OPEN C_DADOSFATURAR FOR
        SELECT LCC2.LINHA, LCC2.QUANTIDADE * LCC2.PRECO_UNITARIO
        FROM LINHA_CONTA_CONSUMO LCC2
        WHERE LCC2.ID_CONTA_CONSUMO = AUX_IDCC;

    -- INICIAR O CONTADOR DE LINHAS DA FATURA A 0
    AUX_CONTADOR_LINHAFAT := 0;

    -- VAMOS CRIAR AS LINHAS DA FATURA COM OS VALORES ID_FATURA, LINHA_FATURA, ID_CONTACONSUMO, LINHA_CONTACONSUMO,
    -- VALORCONSUMO
    LOOP
        FETCH C_DADOSFATURAR INTO AUX_LCC, AUX_VALORCONSUMO;
        INSERT INTO LINHA_FATURA VALUES (AUX_IDFATURA, AUX_CONTADOR_LINHAFAT, AUX_IDCC, AUX_LCC, AUX_VALORCONSUMO);
        AUX_CONTADOR_LINHAFAT := AUX_CONTADOR_LINHAFAT + 1;
        EXIT WHEN C_DADOSFATURAR%NOTFOUND;
    END LOOP;

    -- CALCULA O VALOR TOTAL A PAGAR PELA ESTADIA TENDO EM CONTA A ÉPOCA DO ANO EM QUE A RESERVA FOI FEITA, USANDO
    -- UMA INNER QUERY (SELECT DENTRO DE SELECT)
    SELECT PCTQ.PRECO * (TRUNC(LINHA_RESERVA.DATA_SAIDA) - TRUNC(LINHA_RESERVA.DATA_SAIDA))
    INTO VALOR_ESTADIA
    FROM PRECO_EPOCA_TIPO_QUARTO PCTQ
    WHERE PCTQ.ID_TIPO_QUARTO = LINHA_RESERVA.ID_TIPO_QUARTO
      AND PCTQ.ID_EPOCA = (SELECT E.ID
                           FROM EPOCA E
                           WHERE (LINHA_RESERVA.DATA_ENTRADA) BETWEEN E.DATA_INI AND E.DATA_FIM
    );

    -- CRIA O CHECKOUT DO QUARTO/RESERVA
    INSERT INTO CHECKOUT VALUES (LINHA_RESERVA.ID, LINHA_RESERVA.DATA_SAIDA, '', 0);

    -- CRIA A FATURA ASSOCIADO À RESERVA
    INSERT INTO FATURA
    VALUES (AUX_IDFATURA, AUX_NUMFATURA, SYSDATE, LINHA_RESERVA.ID_CLIENTE, LINHA_RESERVA.ID, VALOR_ESTADIA,
            CONSUMO_TOTAL);

END;

DECLARE
    AUX_NUMFATURA NUMBER;
    AUX_IDFATURA  NUMBER;
BEGIN

    DBMS_OUTPUT.PUT_LINE('ID FATURA: ' || AUX_IDFATURA || ' NUM FATURA: ' || AUX_NUMFATURA);
END;