CREATE OR REPLACE TRIGGER TRGATUALIZACLIENTE
    BEFORE UPDATE
    ON RESERVA
    FOR EACH ROW
DECLARE
    AUX_NOMECLIENTE VARCHAR2(250);
    AUX_NIF         NUMBER;
    AUX_EMAIL       VARCHAR2(250);
    AUX_TELEFONE    NUMBER;
BEGIN

    SELECT C.NOME, C.NIF, C.EMAIL, C.TELEFONE
    INTO AUX_NOMECLIENTE, AUX_NIF, AUX_EMAIL, AUX_TELEFONE
    FROM CLIENTE C
    WHERE C.ID = :NEW.ID_CLIENTE;

    :NEW.NOME := AUX_NOMECLIENTE;
    :NEW.NIF := AUX_NIF;
    :NEW.EMAIL := AUX_EMAIL;
    :NEW.TELEFONE := AUX_TELEFONE;

END;

-- TEST

-- ATUALIZA OS DADOS DA RESERVA Nº207 COM OS DADOS DO CLIENTE 86
UPDATE RESERVA
SET ID_CLIENTE = 86
WHERE ID = 207